services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DATABASE=skilldatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_ROOT_PASSWORD=verysecret'
      - 'POSTGRES_USER=user'
    ports:
      - '5432:5432'
